### ISSUE TITLE
Smartstore doesn't work on Galaxy S6 (64-bit) ?

### ISSUE THREAD

**Issue by lingjunjiang** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#138]
Hi friends,

It seems the Smartstore plugin (Mobile SDK 4.0.0) doesn't work on my Galaxy S6 (Android 5.1.1). All work well if I don't use Smartstore. The error message is 

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.oinio.linde.accura-2/base.apk"],nativeLibraryDirectories=[/data/app/com.oinio.linde.accura-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libstlport_shared.so"
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                          at java.lang.System.loadLibrary(System.java:988)
                                                                          at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:173)
                                                                          at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:169)
                                                                          at com.salesforce.androidsdk.smartstore.store.DBOpenHelper.<init>(DBOpenHelper.java:132)
                                                                          at com.salesforce.androidsdk.smartstore.store.DBOpenHelper.getOpenHelper(DBOpenHelper.java:124)
                                                                          at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:202)
                                                                          at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:184)
                                                                          at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.getSmartStore(SmartStorePlugin.java:577)
                                                                          at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.soupExists(SmartStorePlugin.java:306)
                                                                          at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$1400(SmartStorePlugin.java:58)
                                                                          at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run(SmartStorePlugin.java:160)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:818)

Could anyone help to let me know how to solve this problem? Really appreciate it.

Best Regards,
Lingjun

**Comment by toddhalfpenny** [comment]
@lingjunjiang Hi, I have been having similar issues (see this thread that I have accidentally hikjacked) https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/970

I am able to resolve it by changing a line in the *platforms/android/SmartStore/build.gradle* file. Can you try changing the line that specifies the *jniLibs.srcDir* to be like this;

```
jniLibs.srcDir 'libs'
```

Once I had done this I could use the SmartStore again.

I'm currently just testing this out on a variety of devices/emulators to see if it works on them, if so I'll create a PR.

Please let me know if this works for you too.

**Comment by toddhalfpenny** [comment]
I have created an issue on the SalesforceMobileSDK-Android repo.
https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1017

And this is the PR for the fix https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1018

**Comment by lingjunjiang** [comment]
@toddhalfpenny Hi, thanks for the tips. However, this doesn't work for me. I finally found the root cause but still doesn't figure out the solution. The problem now is the conflict between Scandit plugin and SmartStore plugin. SmartStore works perfect if Scandit is not installed (no matter jniLibs.srcDir is libs or the current value). However, once Scandit is installed, even jniLibs.srcDir is libs, the same error message happens.

Any suggestion on this? Thanks

**Comment by lingjunjiang** [comment]
@toddhalfpenny The difference between not installing and installing the Scandit is that there is a "libs" folder being created under app root. I guess this causes the conflict. 

Below is the screenshot for the created libs folder by Scandit plugin
![screen shot 2015-12-24 at 12 19 47 pm](https://cloud.githubusercontent.com/assets/4828520/11989475/ef48ddfc-aa38-11e5-84b9-b6a5cbbd5de5.png)

Below is the screenshot for the libs folder in SmartStore plugin
![screen shot 2015-12-24 at 12 20 07 pm](https://cloud.githubusercontent.com/assets/4828520/11989480/0f5a8d48-aa39-11e5-98ad-f3284198a96e.png)

So is there a way to make both work? Thanks

**Comment by lingjunjiang** [comment]
I managed to find a workaround to solve this problem as follows:

1. Ensure SmartStore build.gradle’s jniLibs links to a blank folder, so no .so files would be loaded in SmartStore aar file.  e.x. jniLibs.srcDirs = ['../../external/libs’]
2. Clear SmartStore build folder so no cached .so files are in aar file.
3. Copy .so files from SmartStore/libs to [root]/libs.
4. Delete arm64-v8a folder in [root]/libs, otherwise it needs a 64-bit .so file for SmartStore which I cannot find for it.
5. Rebuild [root]/build.gradle.

It works fine with Scandit and SmartStore for me now.
