### ISSUE TITLE
cordova prepare - Error: TypeError: Cannot read property 'attrib' of null

### ISSUE THREAD

**Issue by arturkryczka** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#203]
Hi,

I followed instruction :

npm install cordova -g

cordova create TestApp
cd TestApp
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
cordova platform add android
cordova platform add ios
cordova prepare

and i have:

`Error: TypeError: Cannot read property 'attrib' of null
    at Object.setOrientation (C:\github projects\sf\TestApp\platforms\android\cordova\lib\AndroidManifest.js:85:32)
    at updateProjectAccordingTo (C:\github projects\sf\TestApp\platforms\android\cordova\lib\prepare.js:134:10)
    at C:\github projects\sf\TestApp\platforms\android\cordova\lib\prepare.js:41:16
    at _fulfilled (C:\github projects\sf\TestApp\platforms\android\cordova\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\github projects\sf\TestApp\platforms\android\cordova\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\github projects\sf\TestApp\platforms\android\cordova\node_modules\q\q.js:796:13)
    at C:\github projects\sf\TestApp\platforms\android\cordova\node_modules\q\q.js:556:49
    at runSingle (C:\github projects\sf\TestApp\platforms\android\cordova\node_modules\q\q.js:137:13)
    at flush (C:\github projects\sf\TestApp\platforms\android\cordova\node_modules\q\q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)`

could you advise?

**Comment by huminzhi** [comment]
@arturkryczka please see the right steps on the README here: https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/tree/unstable
