### ISSUE TITLE
No resource found that matches the given name (at 'icon' with value '@drawable/sf__icon')

### ISSUE THREAD

**Issue by sndyuk** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#253]
Hi,
I followed the [instructions](https://developer.salesforce.com/docs/atlas.ja-jp.noversion.mobile_sdk.meta/mobile_sdk/dev_hybrid_apps_run.htm) and faced on the build error.
Is there anything I missed?

`cordova -v`
6.4.0

Commands I put:
```
cordova create contactsApp com.salesforce.contactexplorer contactsApp
cd contactsApp
npm install shelljs@0.7.0
cordova plugin add cordova-plugin-contacts
cordova plugin add cordova-plugin-statusbar
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
cordova platform add android@5.0.0 
cordova platform add ios@4.2.0 
cp -RL <local path to SalesforceMobileSDK-Shared>/samples/contactexplorer/* www/
cordova prepare
cordova build
```

Then I got the error message:
```
:processDebugManifest
Warning: /hoge/contactsApp/platforms/android/AndroidManifest.xml:30:9-104 Warning:
        Element activity#com.adobe.phonegap.push.PushHandlerActivity at AndroidManifest.xml:30:9-104 duplicated with element declared at AndroidManifest.xml:6:9-104
/hoge/contactsApp/platforms/android/AndroidManifest.xml:30:9-104 Warning:
        Element activity#com.adobe.phonegap.push.PushHandlerActivity at AndroidManifest.xml:30:9-104 duplicated with element declared at AndroidManifest.xml:6:9-104
:processDebugResources
/hoge/contactsApp/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:38:23-41 : No resource found that matches the given name (at 'icon' with value '@drawable/sf__icon').

:processDebugResources FAILED

FAILURE: Build failed with an exception.
```

Thanks.

`cordova build -d`
```
No scripts found for hook "before_build".
No scripts found for hook "before_prepare".
Checking config.xml for saved platforms that haven't been added to the project
Checking for any plugins added to the project that have not been installed in android platform
No differences found between plugins added to project and installed in android platform. Continuing...
Checking for any plugins added to the project that have not been installed in ios platform
No differences found between plugins added to project and installed in ios platform. Continuing...
Generating config.xml from defaults for platform "android"
Generating platform-specific config.xml from defaults for iOS at /hoge/contactsApp/platforms/ios/contactsApp/config.xml
Merging project's config.xml into platform-specific iOS config.xml
Merging and updating files from [www, platforms/ios/platform_www] to platforms/ios/www
Wrote out Android application name to "contactsApp"
Wrote out Android package name to "com.salesforce.contactexplorer"
This app does not have launcher icons defined
updated project successfully
Wrote out iOS Bundle Identifier "com.salesforce.contactexplorer" and iOS Bundle Version "1.0.0" to /hoge/contactsApp/platforms/ios/contactsApp/contactsApp-Info.plist
iOS Product Name has not changed (still "contactsApp")
This app does not have icons defined
This app does not have splash screens defined
Prepared iOS project successfully
Executing script found in plugin com.salesforce for hook "after_prepare": plugins/com.salesforce/tools/after-prepare-android.js
Removing duplicate entry from AndroidManifest.xml.
Removed duplicate entry in AndroidManifest.xml.
Checking config.xml for saved plugins that haven't been added to the project
No scripts found for hook "before_compile".
ANDROID_HOME=/hoge/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:compileReleaseJavaWithJavac UP-TO-DATE
:CordovaLib:packageReleaseJar UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:prepareComAndroidSupportSupportV132340Library UP-TO-DATE
:prepareComAndroidSupportSupportV42400Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase980Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement980Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGcm980Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesIid980Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasks980Library UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources FAILED

BUILD FAILED

Total time: 2.44 secs
```

**Comment by bhariharan** [comment]
@sndyuk We don't support `cordova build` currently. Please use `Android Studio` to build and run your project. The following steps should work.

```
cordova create contactsApp com.salesforce.contactexplorer contactsApp
cd contactsApp
npm install shelljs@0.7.0
cordova plugin add cordova-plugin-contacts
cordova plugin add cordova-plugin-statusbar
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
cordova platform add android@5.0.0 
cordova platform add ios@4.2.0 
cp -RL <local path to SalesforceMobileSDK-Shared>/samples/contactexplorer/* www/
Import android project into Android Studio
```

Let me know if you run into any issues with this approach (you don't need to explicitly call `cordova prepare` - we call it as part of our plugin addition). Calling it twice is problematic.

**Comment by sndyuk** [comment]
@bhariharan I did the command you've pasted and I tried to open an emulator through Android Studio. I got the another error message:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.salesforce.contactexplorer, PID: 3591
                  java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: com.salesforce.androidsdk.config.BootConfig$BootConfigException: Failed to open www/bootconfig.json
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
                      at android.app.ActivityThread.-wrap1(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: com.salesforce.androidsdk.config.BootConfig$BootConfigException: Failed to open www/bootconfig.json
                      at com.salesforce.androidsdk.config.BootConfig.readBootConfigFile(BootConfig.java:176)
                      at com.salesforce.androidsdk.config.BootConfig.readFromJSON(BootConfig.java:145)
                      at com.salesforce.androidsdk.config.BootConfig.getBootConfig(BootConfig.java:93)
                      at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.getUserAgent(SalesforceHybridSDKManager.java:139)
                      at com.salesforce.androidsdk.app.SalesforceSDKManager.getUserAgent(SalesforceSDKManager.java:878)
                      at com.salesforce.androidsdk.app.SalesforceSDKManager.initInternal(SalesforceSDKManager.java:331)
                      at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.init(SalesforceHybridSDKManager.java:70)
                      at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.initHybrid(SalesforceHybridSDKManager.java:86)
                      at com.salesforce.androidsdk.phonegap.app.HybridApp.onCreate(HybridApp.java:43)
                      at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                      at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                   Caused by: java.io.FileNotFoundException: www/bootconfig.json
                      at android.content.res.AssetManager.openAsset(Native Method)
                      at android.content.res.AssetManager.open(AssetManager.java:313)
                      at android.content.res.AssetManager.open(AssetManager.java:287)
                      at com.salesforce.androidsdk.config.BootConfig.readBootConfigFile(BootConfig.java:171)
                      at com.salesforce.androidsdk.config.BootConfig.readFromJSON(BootConfig.java:145) 
                      at com.salesforce.androidsdk.config.BootConfig.getBootConfig(BootConfig.java:93) 
                      at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.getUserAgent(SalesforceHybridSDKManager.java:139) 
                      at com.salesforce.androidsdk.app.SalesforceSDKManager.getUserAgent(SalesforceSDKManager.java:878) 
                      at com.salesforce.androidsdk.app.SalesforceSDKManager.initInternal(SalesforceSDKManager.java:331) 
                      at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.init(SalesforceHybridSDKManager.java:70) 
                      at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.initHybrid(SalesforceHybridSDKManager.java:86) 
                      at com.salesforce.androidsdk.phonegap.app.HybridApp.onCreate(HybridApp.java:43) 
                      at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707) 
                      at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Project directory structure is like this. I don't have `www` directory which the error message says. :
![image](https://cloud.githubusercontent.com/assets/615630/20786287/eb1a220a-b79c-11e6-9c08-9944074b0c46.png)

**Comment by bhariharan** [comment]
@sndyuk Could you search and locate for `bootconfig.json` in your project? This file contains the required configuration properties for the app to run. Also, which folder did you import in `Android Studio`?

**Comment by sndyuk** [comment]
@bhariharan I imported `[project]/platforms/android` directory into Android Studio. `bootconfig.json` is not located under the dir, but I found `[project]/www/bootconfig.json`.

**Comment by bhariharan** [comment]
@sndyuk Have you tried generating the app using `forcedroid create`?

**Comment by sndyuk** [comment]
@bhariharan Yes, I tried `forcedroid` command before and it seemed working first time. But the problem was that time, I couldn't build anymore, once I executed a cordova command( I forgot what was that exactly... I'll reproduce that later).
Should we use `forcedroid`? What are the difference between `forcedroid create` and `cordova create` which [you wrote](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/253#issuecomment-263945553)?

**Comment by bhariharan** [comment]
@sndyuk `forcedroid create` is the easiest way to get started with a working hybrid app. We automatically run a `postinstall` script that moves files to their required locations so that things work seamlessly. However, our plugin needs to be the last plugin added, since we move stuff around. There are some pain points with adding other plugins that we hope to alleviate in our next release.

**Comment by sndyuk** [comment]
@bhariharan Alright, I'll use `forcedroid` command instead. I look forward to the next release.
For future reference, how can I run the `postinstall` script?

**Comment by bhariharan** [comment]
@sndyuk The `postinstall` script is plugged into `Cordova` as a hook, so there's no need to manually run it. Let me know if `forcedroid` works for you.

**Comment by sndyuk** [comment]
@bhariharan I tried `forcedroid` again and I got the same error(No resource found that matches the given name (at 'icon' with value '@drawable/sf__icon')) when I build on Android Studio after the following steps:
```
forceios create --apptype=hybrid_local --appname=ContactApp2 --companyid=com.sample --organization=Sample --outputdir=.
npm install shelljs@0.7.0
cordova platform add android@5.0.0
(Build was succeed on Android Studio at this time)
cordova plugin remove com.salesforce
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
(Build was failed on Android Studio at this time)
```

It means I can't add any other codrova plugin. Do you have any idea to fix it?(Is it occurred on only my environment?)

**Comment by bhariharan** [comment]
@sndyuk Looks like you used `forceios` to generate the app. Please try with `forcedroid`. We have some issues with adding other plugins, but we will be releasing fixes for those in an upcoming release.

**Comment by bhariharan** [comment]
@sndyuk This is fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/258). It will be a part of our upcoming `Mobile SDK 5.0` release, which is slated to drop sometime this month. #safeharbor

**Comment by sndyuk** [comment]
@bhariharan Thanks! Should I still use `forcedroid create` command on the next release or can I use `cordova create` as [the README](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/258/files#diff-04c6e90faac2675aa89e2176d2eec7d8R9)?

**Comment by bhariharan** [comment]
@sndyuk Both should work, but the preferred approach is to use `forcedroid create` and then add the plugins you need additionally. I will update the README there as well.
