### ISSUE TITLE
Not able to open database after logout on Android

### ISSUE THREAD

**Issue by sevem** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#292]
We store some global informations about the app in a global soup. After logging out an User, it is not possible to login again. It seem's like the password for the database is also deleted during a logout. I was not able to reproduce this behaviour on iOS. So the plugin handles the logout in a different way on different operating systems. The user has to uninstall die app and install it again to solve this problem. Problem is, the app is used by different Salesforce users. So it is necessary to give the users the possibility to logout. To logout the user we are using the logout() function in the sfaccountmanager

```javascript
cordova.require('com.salesforce.plugin.sfaccountmanager').logout();
```

If a new user try's to login we first check if the global soup already exists with 

```javascript
navigator.smartstore.soupExists()
```

And here we got the problem. It is not possible to open the database

```
I/SmartStorePlugin.execute: action: pgSoupExists, jsVersion: 4.3.0
W/SmartStorePlugin.execute: is being called by js from older sdk, jsVersion: 4.3.0, nativeVersion: 4.3.1
D/SmartSTorePlugin.execute: Main thread time for pgSoupExists->0
E/Database: Failed to setLocale() when constructing, closing the database
            net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
            at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
            at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
            at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
            at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
            at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
            at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
            at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1762)
            at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1727)
            at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2344)
            at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1091)
            at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1154)
            at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
            at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
            at com.salesforce.androidsdk.smartstore.store.SmartStore.getDatabase(SmartStore.java:223)
            at com.salesforce.androidsdk.smartstore.store.SmartStore.hasSoup(SmartStore.java:675)
            at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.soupExists(SmartStorePlugin.java:311)
            at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$1500(SmartStorePlugin.java:59)
            at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run(SmartStorePlugin.java:152)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
            at java.lang.Thread.run(Thread.java:762)
```

Currently we still use the plugin version 4.3.1. 

Steps to reproduce:
1. login with a Salesforce user with an Android hybrid app
2. create a global soup
3. store some informations in a global soup
4. exit the application and restart
5. login as a new user and try to check if the global soup already exist and try to query the records

**Comment by sevem** [comment]
verified this issue on Mobile SDK 5.0.0. Still here a problem.

**Comment by bhariharan** [comment]
@sevem Do you have PIN enabled in your org? Do you need the global DB to persist across logins?

**Comment by sevem** [comment]
@bhariharan no, no PIN enabled and yes, the global soup needs to persists across logins. Everything works fine on iOS. The issue occurs only on Android

**Comment by bhariharan** [comment]
Could you debug a bit on the native layer and let me know if the encryption keys being used are the same?

**Comment by sevem** [comment]
@bhariharan I saw that you closed this issue. Unfortunately I was not able to investigate this issue more. But this issue still exists. But what I missed to tell you is, this issue only occurs on Android 7. With a new test device with Android 5 I have no problem

**Comment by sevem** [comment]
@bhariharan I've tried to replace my global soup with a global soup with externalStorage. Same behavior. When a user log's out it seems that the password for the global database / storage is also deleted. The second time I start the app after the logout, the password is different to the first password. 

This issue is getting more and more critical. A lot of customers are affected. And we definitely need the global database because the devices are shared between users and we have to handle multiple logged in users

**Comment by bhariharan** [comment]
This is expected, especially if the org you're using has passcode/PIN protection enabled. If PIN is enabled, the encryption key is derived from the PIN itself for maximum security. If you need to access the global database across logins, you'll need to override `logout`, grab the existing encryption key stored in memory before it's removed, then run `PRAGMA rekey` on the database to re-encrypt it with the new key once login is complete.

**Comment by rajNikP** [comment]
Can you suggest how to overide logout

**Comment by urthakkar** [comment]
@rajNikP please use the sdk v6.0, where we no longer use the Pin for deriving the encryption key
