### ISSUE TITLE
problems installing plugin

### ISSUE THREAD

**Issue by lumon86** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#314]
Hi everyone
Im having problems with this plugin, and that is because i dont have a very good internet connection, so i just downloaded this plugin and when im trying to add the plugin manually i`m having this problem:
Error: Invalid Plugin! ../../plugins/SalesforceMobileSDK-CordovaPlugin-master needs a valid package.json
Im goping crazy because i cant make it work. anybody can help me with this ?

**Comment by bhariharan** [comment]
This is caused by a breaking change in `Cordova 7.0.0`. Please use `Cordova 6.4.0` with this plugin.

**Comment by lumon86** [comment]
Hi @bhariharan when i run the project with android studio the app just crash and the android monitor shows me :

FATAL EXCEPTION: main
                                                                      Process: com.exampleapp.bestapp, PID: 5763
                                                                      java.lang.RuntimeException: Unable to instantiate application com.salesforce.androidsdk.phonegap.app.HybridApp: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.app.HybridApp" on path: DexPathList[[zip file "/data/app/com.exampleapp.bestapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.exampleapp.bestapp-1/lib/arm, /system/lib, /vendor/lib]]
                                                                          at android.app.LoadedApk.makeApplication(LoadedApk.java:802)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5376)
                                                                          at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.app.HybridApp" on path: DexPathList[[zip file "/data/app/com.exampleapp.bestapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.exampleapp.bestapp-1/lib/arm, /system/lib, /vendor/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                          at android.app.Instrumentation.newApplication(Instrumentation.java:1014)
                                                                          at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5376) 
                                                                          at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
