### ISSUE TITLE
App crashing on Android

### ISSUE THREAD

**Issue by lumon86** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#315]
Hello Im having an issue, anytime i run the app with android studio it crashes, this is my output:
```
FATAL EXCEPTION: main
Process: com.exampleapp.bestapp, PID: 5763
java.lang.RuntimeException: Unable to instantiate application com.salesforce.androidsdk.phonegap.app.HybridApp: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.app.HybridApp" on path: DexPathList[[zip file "/data/app/com.exampleapp.bestapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.exampleapp.bestapp-1/lib/arm, /system/lib, /vendor/lib]]
                                                                          at android.app.LoadedApk.makeApplication(LoadedApk.java:802)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5376)
                                                                          at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.app.HybridApp" on path: DexPathList[[zip file "/data/app/com.exampleapp.bestapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.exampleapp.bestapp-1/lib/arm, /system/lib, /vendor/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                          at android.app.Instrumentation.newApplication(Instrumentation.java:1014)
                                                                          at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5376) 
                                                                          at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
```

**Comment by wmathurin** [comment]
It looks like the project creation was not successful, those classes are part of the SalesforceMobileSDK plugin.
Was there any errors or warning when you ran forcedroid?

**Comment by lumon86** [comment]
Hi @wmathurin thanks for the reply:

This was the error:
forcedroid failed

Command failed: cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0 --force

Then i just deleted the plugin, and i download the SalesforceMobileSDK manually and added again manually with the cordova plugin add ../path .
And after i added the plugin manually i get:

Installing "com.salesforce" for android
Dependent plugin "cordova-plugin-whitelist" already installed on android.
Fetching plugin "https://github.com/apache/cordova-plugin-device" via git clone
Repository "https://github.com/apache/cordova-plugin-device" checked out to git ref "r1.0.1".
Dependent plugin "cordova-plugin-device" already installed on android.
Fetching plugin "https://github.com/phonegap/phonegap-plugin-push" via git clone
Repository "https://github.com/phonegap/phonegap-plugin-push" checked out to git ref "1.5.0".
Dependent plugin "phonegap-plugin-push" already installed on android.
--force is used. edit-config will overwrite conflicts if any. Conflicting plugins may not work as expected.
Running SalesforceMobileSDK plugin android post-install script
You must set the ANDROID_HOME environment variable to the path of your installation of the Android SDK.

Thanks you @wmathurin

**Comment by wmathurin** [comment]
Could you run forcedroid again but with the flag --verbose to get more details.
It should help you figure out why it is failing.

**Comment by lumon86** [comment]
Hi @wmathurin this is the error after typing --verbose

forcedroid failed

Command failed: cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0 --force
Error: Failed to fetch plugin https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: git: Command failed with exit code 128 Error output:
Cloning into '/var/folders/s2/bjq3_nkn7glbv6z5knf0wgdr0000gn/T/git/1498007409267'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by wmathurin** [comment]
Try [that](https://gist.github.com/entropiae/a899d8a78dc8a38f505e)

**Comment by wmathurin** [comment]
Please reopen this issue if you are still having a problem and you believe it's a Mobile SDK bug.
