### ISSUE TITLE
Account not found after deep link redirect in Android

### ISSUE THREAD

**Issue by jsitu** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#470]
I verified the deep link is actually working in Android, I can open the app via the custom link. But the app is stuck at this screen after username and password are entered:

![Screenshot_1566325324](https://user-images.githubusercontent.com/3535345/63373830-9b342380-c356-11e9-89e0-4cca2b338f48.png)

I also set `manifestmerger.enabled=true` in the `project.properties` but no luck. It's working in iOS though.

Errors appeared in the log:
```
2019-08-20 14:03:47.775 3502-3502/io.blackthorn.checkin D/IonicDeeplinkPlugin: Got a new intent: blackthorncheckin://bt-check-in-site.herokuapp.com#access_token=00Di0000000IOVO%21AQMAQMjgV.vjdHV8PgnVzFJruYZaXPn5q1LB9ylYpm40DJ3t98a_BA8AXOT6mcJ44UfheqnPyRzkqH5FN64yJqz61qFCdnsb&refresh_token=5Aep861z80Xevi74eU.cCHDMW7H71ODkE.eb.0VqdbJC68KZGW8kYdGIs7fAY3QHHpbvelerQ8rbZIFB.pBE2ou&instance_url=https%3A%2F%2Fuscmarshall.my.salesforce.com&id=https%3A%2F%2Flogin.salesforce.com%2Fid%2F00Di0000000IOVOEA4%2F0050H00000AHKzlQAH&issued_at=1566324228071&signature=vGl%2FAWQq%2FGOMYgUYsaof6wAIQ6E%2BSvH6zb8ISgOQV8U%3D&scope=api+web+refresh_token&token_type=Bearer blackthorncheckin android.intent.action.VIEW blackthorncheckin://bt-check-in-site.herokuapp.com#access_token=00Di0000000IOVO%21AQMAQMjgV.vjdHV8PgnVzFJruYZaXPn5q1LB9ylYpm40DJ3t98a_BA8AXOT6mcJ44UfheqnPyRzkqH5FN64yJqz61qFCdnsb&refresh_token=5Aep861z80Xevi74eU.cCHDMW7H71ODkE.eb.0VqdbJC68KZGW8kYdGIs7fAY3QHHpbvelerQ8rbZIFB.pBE2ou&instance_url=https%3A%2F%2Fuscmarshall.my.salesforce.com&id=https%3A%2F%2Flogin.salesforce.com%2Fid%2F00Di0000000IOVOEA4%2F0050H00000AHKzlQAH&issued_at=1566324228071&signature=vGl%2FAWQq%2FGOMYgUYsaof6wAIQ6E%2BSvH6zb8ISgOQV8U%3D&scope=api+web+refresh_token&token_type=Bearer
2019-08-20 14:03:47.779 3502-3502/io.blackthorn.checkin D/CordovaActivity: Started the activity.
2019-08-20 14:03:47.780 3502-3502/io.blackthorn.checkin D/CordovaActivity: Resumed the activity.
2019-08-20 14:03:47.875 3502-3502/io.blackthorn.checkin I/ClientManager: No user account found
    com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: No user account found
        at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:155)
        at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:139)
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:157)
        at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume(SalesforceActivityDelegate.java:103)
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onResume(SalesforceDroidGapActivity.java:147)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7300)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-08-20 14:03:47.877 3502-3502/io.blackthorn.checkin W/BootConfig: unauthenticatedStartPage set for local app, but it will never be used.
```

**Comment by bhariharan** [comment]
@jsitu We need more information.

- Which version of `Mobile SDK` are you using?
- What type of app is it, i.e. native, hybrid local or hybrid remote?
- How are you deep linking, i.e. where is it triggered from?

The stack trace simply indicates that the authentication flow failed. You need to build a native handler that kicks off auth if required using `Mobile SDK` methods, and then redirects to the URI.

**Comment by jsitu** [comment]
@bhariharan 

- Android 7.1.2 & iOS 4.5.5
- Hybrid (Ionic)
- https://github.com/ionic-team/ionic-plugin-deeplinks, and https://developer.android.com/training/app-links/index.html#web-assoc, I basically followed these steps and created a website that triggers it.

**Comment by bhariharan** [comment]
@jsitu Right - I don't think that'll work out of the box with `Salesforce OAuth`. As I mentioned earlier, you'll need to perform the following steps to get this working:
- You need a custom `Activity` that handles the deeplink URL, and redirects it to login using our `Cordova OAuth` plugin.
- Once login is complete, it'll come back to the custom `Activity` in an authenticated state, at which point you can deeplink to wherever you need to.

I'm not sure how the deeplink plugin works - you'll need to set breakpoints in `SalesforceDroidGapActivity` to figure out where it's failing.

**Comment by jsitu** [comment]
Thanks @bhariharan sounds complicated, will look into it.
