### ISSUE TITLE
App crash on launch on some devices

### ISSUE THREAD

**Issue by jake-moritz-trifecta** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#482]
We are using version 7.3.0 of SalesforceMobileSDK-CordovaPlugin and Cordova Android version 8.0.0. We've recently been experiencing app crashes when our app is opened. The issue seems related to  https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1963. This only started happening a few days ago, despite having upgraded to the specified SF Mobile SDK and Cordova Android versions a month ago. We have not been able to reproduce the issue with local builds, this only happens when our app is built through our Azure DevOps pipeline.

 **SalesforceMobileSDK-CordovaPlugin version**: 7.3.0
**Cordova Android version**: 8.0.0
**Stack trace**:
```
2019-10-22 17:08:54.062 31535-31535/com.mobile.qa D/SalesforceHybridSDKManager: Setting up global store using config found in www/globalstore.json
2019-10-22 17:08:54.211 31535-31535/com.mobile.qa E/Encryptor: Error during asymmetric decryption
    javax.crypto.IllegalBlockSizeException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithPrivateKey(Encryptor.java:365)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSABytes(Encryptor.java:318)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSA(Encryptor.java:299)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:227)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:208)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1126)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:160)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:142)
        at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.setupGlobalStoreFromDefaultConfig(SalesforceHybridSDKManager.java:172)
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onCreate(SalesforceDroidGapActivity.java:111)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.security.KeyStoreException: Unknown error
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithPrivateKey(Encryptor.java:365) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSABytes(Encryptor.java:318) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSA(Encryptor.java:299) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:227) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:208) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105) 
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1126) 
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:160) 
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:142) 
        at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.setupGlobalStoreFromDefaultConfig(SalesforceHybridSDKManager.java:172) 
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onCreate(SalesforceDroidGapActivity.java:111) 
        at android.app.Activity.performCreate(Activity.java:7144) 
        at android.app.Activity.performCreate(Activity.java:7135) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-10-22 17:08:54.214 31535-31535/com.mobile.qa E/SalesforceKeyGenerator: Exception thrown while getting encryption key
    java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:209)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1126)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:160)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:142)
        at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.setupGlobalStoreFromDefaultConfig(SalesforceHybridSDKManager.java:172)
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onCreate(SalesforceDroidGapActivity.java:111)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by bhariharan** [comment]
@jake-moritz-trifecta Which device are you using? This seems like a key mismatch issue. Could you try uninstalling and reinstalling the app and check if the issue still exists?

**Comment by jake-moritz-trifecta** [comment]
> @jake-moritz-trifecta Which device are you using? This seems like a key mismatch issue. Could you try uninstalling and reinstalling the app and check if the issue still exists?

We've seen this happening on a Samsung Galaxy S8 and a Google Pixel 3a. Reinstalling the app does not solve the issue. Oddly enough, builds from yesterday that were previously crashing due to the issue have begun to function properly.

**Comment by jake-moritz-trifecta** [comment]
@bhariharan We are still experiencing this issue. Something else to note is that we have not been able to reproduce this issue in a local environment. We have only seen this issue with builds run through Azure DevOps and installed from AppCenter.

**Comment by jake-moritz-trifecta** [comment]
Closing due to resolution of issue here: https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2013#issuecomment-560213303
